"""
Django settings for chatbot_server project.

Generated by 'django-admin startproject' using Django 3.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-ii_#sz-0vh@^7*)jaru*91u5pxfr8w%8xy8j#*cgh-69+axd9v'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'chatbot_server.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'chatbot_server.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CHATTERBOT = {
    "name" : "S J Bot",
    "logic_adapters": [
    {
        "import_path": "chatterbot.logic.BestMatch",
        "default_response": "I am sorry, but I do not understand.",
        "maximum_similarity_threshold": 0.90
    },
    {
        "import_path": "chatterbot.logic.SpecificResponseAdapter",
        "input_text": "Help me!",
        "output_text": "Ok, here is a link: http://chatterbot.rtfd.org"
    },
    {
        "import_path": "chatterbot.logic.SpecificResponseAdapter",
        "input_text": "Help me",
        "output_text": "Ok, here is a link: http://chatterbot.rtfd.org"
    },
    {
        "import_path": "chatterbot.logic.SpecificResponseAdapter",
        "input_text": "help",
        "output_text": "Ok, here is a link: http://chatterbot.rtfd.org"
    },
    {
        "import_path": "chatterbot.logic.SpecificResponseAdapter",
        "input_text": "Where am i?",
        "output_text": "You are in a magic world."
    },
    {
        "import_path": "chatterbot.logic.SpecificResponseAdapter",
        "input_text": "where am i",
        "output_text": "You are in a magic world."
    },
    {
        "import_path": "chatterbot.logic.SpecificResponseAdapter",
        "input_text": "what should i do",
        "output_text": "You can talk to someone to ask for help."
    }
    ],
    'trainer': 'chatterbot.trainers.ListTrainer',
    'training_data': [
        'How can I help you?',
        'I want to create a chat bot',
        'Have you read the documentation?',
        'No, I have not',
        'This should help get you started: http://chatterbot.rtfd.org/en/latest/quickstart.html',
        'How are you?',
        'I like playing Ping-pong',
        'I am a good programmer',
        'I was born in 2021',
        "I don't know.",
        'My father is a student at The University of Arizona',
        'ehm...',
        'I guess so',
        'I have no idea',
        'I cannot tell you',
        "Think about your goal.",
        "Maybe try another way?"
    ]
    # "storage_adapter": "storage_adapter='chatterbot.storage.SQLStorageAdapter"


}
